# Generated by Django 4.2.23 on 2025-08-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('num_balcony_seats', models.PositiveIntegerField()),
                ('num_ordinary_seats', models.PositiveIntegerField()),
                ('price_balcony', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_ordinary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
