# Generated by Django 4.2.23 on 2025-08-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='num_balcony_seats',
            new_name='balcony_seats',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='num_ordinary_seats',
            new_name='ordinary_seats',
        ),
    ]
